### ISSUE TITLE
Create function outputting global coordinates

### ISSUE THREAD

**Issue by fgnievinski** [vitorhjr/geo-alhazen#13]
get_reflection_spherical_global

**Comment by vitorhjr** [comment]
A draft of the function:

```
function [X, Y] = get_quasigeo_coord (x,y,Rs)

Y = y + Rs;
X = x;

end
```
It needs to input both X and Y or only Y?

**Comment by vitorhjr** [comment]
I upload the function [get_quasigeo_coord](https://github.com/vitorhjr/geo-alhazen/blob/multh/geo-alhazen-aux/get_quasigeo_coord.m) to the branch.

**Comment by vitorhjr** [comment]
I named the function as get_quasigeo_coord. Do you think it better to rename it as get_reflection_spherical_global?

**Comment by fgnievinski** [comment]
get_quasigeo_coord is okay.  get_reflection_spherical_global would be a different function:
https://github.com/vitorhjr/geo-alhazen/blob/multh/get_reflection_spherical_quasigeo.m
