### ISSUE TITLE
Support multiple antenna height

### ISSUE THREAD

**Issue by fgnievinski** [vitorhjr/geo-alhazen#16]

**Comment by fgnievinski** [comment]
implemented for Fujimura, needs to be done for other algorithms.

main change is positions are returned with coordinate in separate variables.

[geo-alhazen.20210929fgn.zip](https://github.com/vitorhjr/geo-alhazen/files/7254273/geo-alhazen.20210929fgn.zip)

demo:
```
e_dom = 1:5:90;
Ha_dom = [10 50 100 200 300 500 1000];
[e_grid, Ha_grid] = meshgrid(e_dom, Ha_dom);

[Di, g, arclen, sldist, xspec, yspec] = get_reflection_spherical (e_grid, Ha_grid);

figure, imagesc(e_dom, Ha_dom, Di)
xlabel('Sat. Elev. (deg.)')
ylabel('Ant. Height (h)')
title('Interf. delay (m)')
grid on
set(gca(), 'YDir','normal')

```
![image](https://user-images.githubusercontent.com/5018500/135328166-5cf4b13e-d727-4a05-bc05-28e987e2d6f6.png)

**Comment by vitorhjr** [comment]
- First demo is running
- Input/output was revised
- Head of function updated
- Other functions get updated in the branch

**Comment by vitorhjr** [comment]
I've done some changes in the first demo as follow:
- remove the loop of antenna heights;
- change inputs of  vectors to matrices of elevation angles and heights

I observed the first demo runs an elevation for each height. The code runs this for each algorithm. For each algorithm loop, only the diagonal elements of the matrix are correct whose we want only results on the spherical horizon. 

Currently, the code section of the loop is:

```
for i=1:n
    Ha = Has(i);
    ehor = ehors(i);
    for j=1:m
        algorithm = algs{j};
        [Di(i,j), g(i,j), arclen(i,j), sldist(i,j), Xspec(i,j),Yspec(i,j)]...
            = get_reflection_spherical (ehor, Ha, [], [], algorithm);
    end
end
```

I suggest the following:
```
for i=1:m
    algorithm = algs{i};
    [Di_aux, g_aux, arclen_aux, sldist_aux, Xspec_aux, Yspec_aux]...
            = get_reflection_spherical (e_grid, Ha_grid, [], [], algorithm);

     [Di(:,i), g(:,i), arclen(:,i), sldist(:,i), Xspec(:,i), Yspec(:,i)] ...
         = get_diag(Di_aux, g_aux, arclen_aux, sldist_aux, Xspec_aux, Yspec_aux);
end
```
Where _get_diag_ is a local function:

```
function [Di, g, arclen, sldist, Xspec, Yspec] = get_diag(Di_aux, g_aux, arclen_aux, sldist_aux, Xspec_aux, Yspec_aux)
     Di = diag(Di_aux).'; 
     g = diag(g_aux).';
     arclen= diag(arclen_aux).';
     sldist= diag(sldist_aux).';
     Xspec= diag(Xspec_aux).';
     Yspec= diag(Yspec_aux).';
end
```

**Comment by fgnievinski** [comment]
you can input the diagonal vectors directly:

```
    for j=1:m
        algorithm = algs{j};
        [Di(i,j), g(i,j), arclen(i,j), sldist(i,j), Xspec(i,j),Yspec(i,j)]...
            = get_reflection_spherical (ehors(:), Has(:), [], [], algorithm);
    end
```

after all, "matrix input may also be a vector or a scalar":
https://github.com/vitorhjr/geo-alhazen/blob/cb7f86693ba571cc95a55e6f1edf1dac1836b60e/get_reflection_spherical.m#L9

**Comment by vitorhjr** [comment]
You're correct. I thought of the input only as a matrix.

**Comment by vitorhjr** [comment]
New releases in the first demo on the commit f3a58a1753cb98155cccc08abc42cc94c0420cd1. I've made the following main changes:
- remove the loop of antenna heights;
- inputs column vectors of elevation angle and antenna heights
- include the new function [geo-alhazen/get_quasigeo_coord](https://github.com/vitorhjr/geo-alhazen/blob/multh/geo-alhazen-aux/get_quasigeo_coord.m)
