### ISSUE TITLE
Simpler demo

### ISSUE THREAD

**Issue by fgnievinski** [vitorhjr/geo-alhazen#19]
We need a simpler demonstration of:
- delay for fixed satellite elevation (10 degrees) and varying antenna height (zero to 500 m)
- delay for fixed antenna height (10 m) and varying satellite elevation (zenith to spherical horizon)

Two figures with line plots only.

**Comment by fgnievinski** [comment]
you could adapt from the demonstrations of curv-altimetry

**Comment by vitorhjr** [comment]
The simpler demos are available.
- Height variation: https://github.com/vitorhjr/geo-alhazen/blob/main/demo/demo1_simpler.m
- Elevation variation: https://github.com/vitorhjr/geo-alhazen/blob/main/demo/demo2_simpler.m
