### ISSUE TITLE
include demo output

### ISSUE THREAD

**Issue by fgnievinski** [vitorhjr/geo-alhazen#22]
the output from demonstrations should be provided for end users.

please save the images in PNG format and the tables in TXT format.

then put output as well as demo scripts in a new "demo" subfolder.

then issue a new minor release (2.0.0.1).

**Comment by fgnievinski** [comment]
I've made two minor bug fixes; please make sure to download the latest version before running the demonstrations.

**Comment by vitorhjr** [comment]
I did each of the specified steps. Besides that, I adjust the function [setup_spherical_reflection](https://github.com/vitorhjr/geo-alhazen/blob/main/demo/setup_spherical_reflection.m) to run inside the [demo folder](https://github.com/vitorhjr/geo-alhazen/tree/main/demo). 

I add the outputs that are in the paper, i.e., tables and the minimum elevation figure. 

I created the new [release v2.0.0.1](https://github.com/vitorhjr/geo-alhazen/releases/tag/2.0.0.1).

**Comment by vitorhjr** [comment]
I will close this issue. If it's needed, please reopen it.
