### ISSUE TITLE
Create function for trigonometric formulas

### ISSUE THREAD

**Issue by fgnievinski** [vitorhjr/geo-alhazen#7]
for interf. delay, slant distance, and height correction.

- Retirar variáveis que não constam no artigo como ... atraso trigonométrico?

_Originally posted by @vitorhjr in https://github.com/vitorhjr/geo-alhazen/issues/2#issuecomment-927940709_

**Comment by vitorhjr** [comment]
I implemented interf. delay, slant distance, and height correction. I commented the implementation in the issue https://github.com/vitorhjr/curv-altimetry-dev/issues/29. 

I will repost here the comments about the findings.

**Comment by vitorhjr** [comment]
I have been modeling the trigonometric approach for the altimetry correction and reflection on a sphere (deposited in geo-alhazen repository). Those are the new trigonometric functions in the branch cor-trig: 

- [get_spherical_reflection_trig](https://github.com/vitorhjr/geo-alhazen/blob/main/get_spherical_reflection_trig.m): compute interf. delay and slant distance;
- [get_curvature_altimetry_correction_pdoppler_series_trig](https://github.com/vitorhjr/curv-altimetry-dev/blob/cor-trig/get_curvature_altimetry_correction_pdoppler_series_trig.m): compute altimetry correction
- [demo_trig1](https://github.com/vitorhjr/curv-altimetry-dev/blob/cor-trig/demo/demo_trig1.m): demonstration of trigonometric altimetry correction

**Comment by vitorhjr** [comment]
I found some issues when implementing the formulas from my master's thesis:

- The correct formula for the discrepancies between direct and reflected elevation angles is $\Delta e_r = e_d - e_r^s$. In the thesis, it's presented as $\Delta e_r = -e_d - e_r^s$ (p. 69, eq. 114);
- The second formula for $D_i$ (p. 73, eq. 123) is incorrect. It should be reformulated or discarded. The first formula $D_i  = D_l^s*(\sqrt\gamma- sin(g))$ is correct;
- The formula of altimetry correction on eq. 126 (p. 74) is not correct. It should be revised and reformulated. To compute altimetry correction I'm using the gradient.

**Comment by vitorhjr** [comment]
Although those issues, the implementation of the trigonometric formulas is correct in the algorithms.
